### ISSUE TITLE
Wouldn't this be more useful as Test class?

### ISSUE THREAD

**Issue by rsoesemann** [pozil/legacy-api-scanner#2]
which every developer could add to his nightly Test Suite run or into her DevOps pipeline to auto-detect wrong API usage?

**Comment by pozil** [comment]
Hi @rsoesemann this is a good question that deserves a conversation.

This code is meant to detect legacy API calls on productions orgs. In an ideal world, all Salesforce integrations would also have an equivalent test instance that is part of the DevOps pipeline so you could run this scanner as a test on a sandbox and detect issues early.
However, we all know that things are so not well organized and clean for all Salesforce orgs. Some integrations don't even use sandboxes and there could also be users that are directly using clients on their local machines to call APIs on prod.

This means that we would need to run those nightly tests directly in production org in order to catch all issues.
Do you feel that it's something that it would make sense as part of a DevOps pipeline?
I don't pretend that I have the answer yet but I'm happy discuss it and if need be, also ship a test equivalent of the anonymous Apex if you feel that's useful.

**Comment by pozil** [comment]
Learn more about our plan for legacy API retirement and what it means for you. Get tips on how to upgrade integrations using legacy APIs, as well as guidance on how to plan for the future.

In this post, we’ll present Salesforce’s plan for legacy API retirement. We’ll provide resources such as a utility script and instructions to help you identify if you are affected. You’ll get tips on how to upgrade integrations using legacy APIs and guidance on how to plan for the future.

**Comment by pozil** [comment]
A test version of the scanner can be found here:
https://github.com/trailheadapps/apex-recipes/blob/main/force-app/tests/CI%20Recipes/DeprecatedAPIVersionScanner_Tests.cls
